steps:
  # Paso 0: Compilar el proyecto con Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'backend'

  # Paso 1: Listar archivos para verificar (Opcional, ayuda a depurar)
  - name: 'ubuntu'
    args: ['ls', '-R', 'backend/target']

  # Paso 2: Construir la imagen de Docker (Corregido con :latest y ruta ./backend)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/api-de-skincare/cloud-run-source-deploy/skincare-api:latest', 
      '-f', 'backend/Dockerfile', 
      './backend'
    ]

  # Paso 3: Subir la imagen al registro
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/api-de-skincare/cloud-run-source-deploy/skincare-api:latest']

  # Paso 4: Desplegar en Cloud Run con las variables y permisos correctos
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'services', 'update', 'api-skincare-v2',
        '--image=us-central1-docker.pkg.dev/api-de-skincare/cloud-run-source-deploy/skincare-api:latest',
        '--region=us-central1',
        '--add-cloudsql-instances=api-de-skincare:us-central1:skincare',
        '--set-env-vars=DB_NAME=skincare_db,DB_USER=postgres,DB_PASSWORD=Aa1002416662,INSTANCE_CONNECTION_NAME=api-de-skincare:us-central1:skincare',
        '--timeout=600',
        '--cpu=2',
        '--memory=2Gi',
        '--quiet'
      ]

images:
  - 'us-central1-docker.pkg.dev/api-de-skincare/cloud-run-source-deploy/skincare-api:latest'